name: Deploy to Yandex Cloud
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install YC CLI
        run: curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
      - name: Deploy
        env:
          YC_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        run: |
          source /home/runner/yandex-cloud/path.bash.inc
          yc config set service-account-key "$YC_SERVICE_ACCOUNT_KEY_FILE"
          yc serverless function version create --function-name "ИМЯ_ВАШЕЙ_ФУНКЦИИ" --runtime python311 --entrypoint index.handler --memory 128mb --execution-timeout 5s --source-path . --environment VK_TOKEN=${{ secrets.VK_TOKEN }}
